In [1]:
import numpy as np
import pandas as pd
import pims

%config InlineBackend.figure_format='retina'

## RGB values of capillary imaes with known pH

In [1]:
## Read microscopy images of solutions with known pH values and extract their corresponding RGB color values for calibration.

## pH 10

In [2]:
path = 'settings 1/pH 10 capillary 1 image i.2024-08-21-17-12-09/'
image = pims.open(path+'pH 10 capillary 1 image i_Bottom Slide_D_p00_0_A01f00d4.PNG')
rgb_10_1 = np.mean(image[0], axis=(0,1))
print(rgb_10_1)

[ 77.18475292  86.37562203 124.2917501  254.99994796]


In [3]:
path = 'settings 1/pH 10 capillary 1 image ii.2024-08-21-17-13-24/'
image = pims.open(path+'pH 10 capillary 1 image ii_Bottom Slide_D_p00_0_A01f01d4.PNG')
rgb_10_2 = np.mean(image[0], axis=(0,1))
print(rgb_10_2)

[ 70.59138209  78.99172067 114.16843527 254.99994796]


In [4]:
path = 'settings 1/pH 10 capillary 1 image iii.2024-08-21-17-13-34/'
image = pims.open(path+'pH 10 capillary 1 image iii_Bottom Slide_D_p00_0_A01f02d4.PNG')
rgb_10_3 = np.mean(image[0], axis=(0,1))
print(rgb_10_3)

[ 73.40425444  82.1685629  118.62119505 254.99994796]


In [5]:
rgb_10 = np.row_stack((rgb_10_1, rgb_10_2, rgb_10_3))
rgb_10

array([[ 77.18475292,  86.37562203, 124.2917501 , 254.99994796],
       [ 70.59138209,  78.99172067, 114.16843527, 254.99994796],
       [ 73.40425444,  82.1685629 , 118.62119505, 254.99994796]])

## pH 9.5

In [6]:
path = 'settings 1/pH 9.5 capillary 1 image i.2024-08-21-17-35-59/'
image = pims.open(path+'pH 9.5 capillary 1 image i_Bottom Slide_D_p00_0_A01f16d4.PNG')
rgb_95_1 = np.mean(image[0], axis=(0,1))
print(rgb_95_1)

[ 79.85386412  88.42678833 120.77131617 254.99994796]


In [7]:
path = 'settings 1/pH 9.5 capillary 1 image ii.2024-08-21-17-36-14/'
image = pims.open(path+'pH 9.5 capillary 1 image ii_Bottom Slide_D_p00_0_A01f17d4.PNG')
rgb_95_2 = np.mean(image[0], axis=(0,1))
print(rgb_95_2)

[ 78.41865025  86.85279137 119.17462455 254.99994796]


In [8]:
path = 'settings 1/pH 9.5 capillary 1 image iii.2024-08-21-17-36-28/'
image = pims.open(path+'pH 9.5 capillary 1 image iii_Bottom Slide_D_p00_0_A01f18d4.PNG')
rgb_95_3 = np.mean(image[0], axis=(0,1))
print(rgb_95_3)

[ 80.08312847  88.71496425 121.54752522 254.99994796]


In [9]:
rgb_95 = np.row_stack((rgb_95_1, rgb_95_2, rgb_95_3))
rgb_95

array([[ 79.85386412,  88.42678833, 120.77131617, 254.99994796],
       [ 78.41865025,  86.85279137, 119.17462455, 254.99994796],
       [ 80.08312847,  88.71496425, 121.54752522, 254.99994796]])

## pH 9

In [10]:
path = 'settings 1/pH 9 capillary 1 image i.2024-08-21-17-15-00/'
image = pims.open(path+'pH 9 capillary 1 image i_Bottom Slide_D_p00_0_A01f03d4.PNG')
rgb_9_1 = np.mean(image[0], axis=(0,1))
print(rgb_9_1)

[ 89.8124904   96.30634603 115.84273146 254.99994796]


In [11]:
path = 'settings 1/pH 9 capillary 1 image ii.2024-08-21-17-15-14/'
image = pims.open(path+'pH 9 capillary 1 image ii_Bottom Slide_D_p00_0_A01f04d4.PNG')
rgb_9_2 = np.mean(image[0], axis=(0,1))
print(rgb_9_2)

[ 91.18764002  97.73737671 116.85329383 254.99994796]


In [12]:
path = 'settings 1/pH 9 capillary 1 image iii.2024-08-21-17-15-27/'
image = pims.open(path+'pH 9 capillary 1 image iii_Bottom Slide_D_p00_0_A01f05d4.PNG')
rgb_9_3 = np.mean(image[0], axis=(0,1))
print(rgb_9_3)

[ 89.67877707  96.09546336 115.20996543 254.99994796]


In [13]:
rgb_9 = np.row_stack((rgb_9_1, rgb_9_2, rgb_9_3))
rgb_9

array([[ 89.8124904 ,  96.30634603, 115.84273146, 254.99994796],
       [ 91.18764002,  97.73737671, 116.85329383, 254.99994796],
       [ 89.67877707,  96.09546336, 115.20996543, 254.99994796]])

## pH 8.5

In [14]:
path = 'settings 1/pH 8.5 capillary 1 image i.2024-08-21-17-17-23/'
image = pims.open(path+'pH 8.5 capillary 1 image i_Bottom Slide_D_p00_0_A01f06d4.PNG')
rgb_85_1 = np.mean(image[0], axis=(0,1))
print(rgb_85_1)

[106.10575622 107.61250341 101.98179768 254.99994796]


In [15]:
path = 'settings 1/pH 8.5 capillary 1 image ii.2024-08-21-17-17-33/'
image = pims.open(path+'pH 8.5 capillary 1 image ii_Bottom Slide_D_p00_0_A01f07d4.PNG')
rgb_85_2 = np.mean(image[0], axis=(0,1))
print(rgb_85_2)

[106.90805598 108.44517682 102.34877113 254.99994796]


In [16]:
path = 'settings 1/pH 8.5 capillary 1 image iii.2024-08-21-17-17-55/'
image = pims.open(path+'pH 8.5 capillary 1 image iii_Bottom Slide_D_p00_0_A01f09d4.PNG')
rgb_85_3 = np.mean(image[0], axis=(0,1))
print(rgb_85_3)

[109.81172433 111.40805598 105.37455733 254.99994796]


In [17]:
rgb_85 = np.row_stack((rgb_85_1, rgb_85_2, rgb_85_3))
rgb_85

array([[106.10575622, 107.61250341, 101.98179768, 254.99994796],
       [106.90805598, 108.44517682, 102.34877113, 254.99994796],
       [109.81172433, 111.40805598, 105.37455733, 254.99994796]])

## pH 8

In [18]:
path = 'settings 1/pH 8 capillary 1 image i.2024-08-21-17-19-33/'
image = pims.open(path+'pH 8 capillary 1 image i_Bottom Slide_D_p00_0_A01f10d4.PNG')
rgb_8_1 = np.mean(image[0], axis=(0,1))
print(rgb_8_1)

[120.94736258 119.04650172  99.83216848 254.99994796]


In [19]:
path = 'settings 1/pH 8 capillary 1 image ii.2024-08-21-17-19-47/'
image = pims.open(path+'pH 8 capillary 1 image ii_Bottom Slide_D_p00_0_A01f11d4.PNG')
rgb_8_2 = np.mean(image[0], axis=(0,1))
print(rgb_8_2)

[125.42442258 123.37337338 102.44742919 254.99994796]


In [20]:
path = 'settings 1/pH 8 capillary 1 image iii.2024-08-21-17-20-01/'
image = pims.open(path+'pH 8 capillary 1 image iii_Bottom Slide_D_p00_0_A01f12d4.PNG')
rgb_8_3 = np.mean(image[0], axis=(0,1))
print(rgb_8_3)

[126.99030686 124.83315759 103.37429495 254.99994796]


In [21]:
rgb_8 = np.row_stack((rgb_8_1, rgb_8_2, rgb_8_3))
rgb_8

array([[120.94736258, 119.04650172,  99.83216848, 254.99994796],
       [125.42442258, 123.37337338, 102.44742919, 254.99994796],
       [126.99030686, 124.83315759, 103.37429495, 254.99994796]])

## pH 7.5

In [22]:
path = 'settings 1/pH 7.5 capillary 1 image i.2024-08-21-17-23-35/'
image = pims.open(path+'pH 7.5 capillary 1 image i_Bottom Slide_D_p00_0_A01f13d4.PNG')
rgb_75_1 = np.mean(image[0], axis=(0,1))
print(rgb_75_1)

[137.40178399 132.84794744 102.88632007 254.99994796]


In [23]:
path = 'settings 1/pH 7.5 capillary 1 image ii.2024-08-21-17-23-50/'
image = pims.open(path+'pH 7.5 capillary 1 image ii_Bottom Slide_D_p00_0_A01f14d4.PNG')
rgb_75_2 = np.mean(image[0], axis=(0,1))
print(rgb_75_2)

[136.46910624 131.99985038 101.91378711 254.99994796]


In [24]:
path = 'settings 1/pH 7.5 capillary 1 image iii.2024-08-21-17-24-08/'
image = pims.open(path+'pH 7.5 capillary 1 image iii_Bottom Slide_D_p00_0_A01f15d4.PNG')
rgb_75_3 = np.mean(image[0], axis=(0,1))
print(rgb_75_3)

[137.174496   132.67661299 102.56379455 254.99994796]


In [25]:
rgb_75 = np.row_stack((rgb_75_1, rgb_75_2, rgb_75_3))
rgb_75

array([[137.40178399, 132.84794744, 102.88632007, 254.99994796],
       [136.46910624, 131.99985038, 101.91378711, 254.99994796],
       [137.174496  , 132.67661299, 102.56379455, 254.99994796]])

## Summary

In [26]:
pH = np.array([7.5, 7.5, 7.5, 8, 8, 8, 8.5, 8.5, 8.5, 9, 9, 9, 9.5, 9.5, 9.5, 10, 10, 10])
rgb = np.column_stack((pH, np.row_stack((rgb_75, rgb_8, rgb_85, rgb_9, rgb_95, rgb_10))))
rgb

array([[  7.5       , 137.40178399, 132.84794744, 102.88632007,
        254.99994796],
       [  7.5       , 136.46910624, 131.99985038, 101.91378711,
        254.99994796],
       [  7.5       , 137.174496  , 132.67661299, 102.56379455,
        254.99994796],
       [  8.        , 120.94736258, 119.04650172,  99.83216848,
        254.99994796],
       [  8.        , 125.42442258, 123.37337338, 102.44742919,
        254.99994796],
       [  8.        , 126.99030686, 124.83315759, 103.37429495,
        254.99994796],
       [  8.5       , 106.10575622, 107.61250341, 101.98179768,
        254.99994796],
       [  8.5       , 106.90805598, 108.44517682, 102.34877113,
        254.99994796],
       [  8.5       , 109.81172433, 111.40805598, 105.37455733,
        254.99994796],
       [  9.        ,  89.8124904 ,  96.30634603, 115.84273146,
        254.99994796],
       [  9.        ,  91.18764002,  97.73737671, 116.85329383,
        254.99994796],
       [  9.        ,  89.67877707,  96.095

# Export

In [27]:
df = pd.DataFrame(rgb, columns = ['pH','R','G','B', '4th channel'])
df

pH           R           G           B  4th channel
0    7.5  137.401784  132.847947  102.886320   254.999948
1    7.5  136.469106  131.999850  101.913787   254.999948
2    7.5  137.174496  132.676613  102.563795   254.999948
3    8.0  120.947363  119.046502   99.832168   254.999948
4    8.0  125.424423  123.373373  102.447429   254.999948
5    8.0  126.990307  124.833158  103.374295   254.999948
6    8.5  106.105756  107.612503  101.981798   254.999948
7    8.5  106.908056  108.445177  102.348771   254.999948
8    8.5  109.811724  111.408056  105.374557   254.999948
9    9.0   89.812490   96.306346  115.842731   254.999948
10   9.0   91.187640   97.737377  116.853294   254.999948
11   9.0   89.678777   96.095463  115.209965   254.999948
12   9.5   79.853864   88.426788  120.771316   254.999948
13   9.5   78.418650   86.852791  119.174625   254.999948
14   9.5   80.083128   88.714964  121.547525   254.999948
15  10.0   77.184753   86.375622  124.291750   254.999948
16  10.0   70.591382   78.991721  114.168435   254.999948
17  10.0   73.404254   82.168563  118.621195   254.999948

In [28]:
df.to_csv('pH_calibration_capillary_data (24.08.21 settings 1 nm).csv')

## RGB values of capillary images with known pH

In [ ]:
directory = '/'
p = 2880 # time index 
f = 4 # location index 

In [ ]:
filename = '.PNG'%(p,f)

image = pims.open(directory+filename)[0]

In [ ]:
num_items = len(os.listdir(directory))
num_items

In [ ]:
Ly,Lx,Lt = image.shape
Ly

In [ ]:
# Create the pandas DataFrame with column name is provided explicitly
df_pixel = pd.DataFrame(columns=['time','loc','x', 'r','g','b','unknown'])

for p in range(0,2881,1):
    for f in range(4,5,1):
        filename = '24.11.14 10 mM Bicarbonate, 20 mM HCl with Droplets_Top Slide_R_p%02d_0_A01f%02dd4.PNG'%(p,f)
        print(directory+filename)
        try:
            image = pims.open(directory+filename)[0]
            #if len(image.shape) > 2 and image.shape[2]==4:
                #image = image[:,:,:3]
            img = image
            rgb = np.mean(img,axis=0)
            rows = {'time': p*np.ones((Lx,), dtype=int),
                    'loc': f*np.ones((Lx,), dtype=int),
                    'x': np.arange(Lx),
                    'r': rgb[:,0],
                    'g': rgb[:,1],
                    'b': rgb[:,2]}
                   #'unknown': rgb[:,3]}
            new_df_pixel = pd.DataFrame(rows)
            df_pixel = pd.concat([df_pixel,new_df_pixel], ignore_index=True)
        except:
            print('no such file!')

In [ ]:
#plot RGB values
loc = 4 # time index
time = 1 # space index

idx2 = (df_pixel['time']==time) & (df_pixel['loc']==loc)



plt.plot(df_pixel['x'][idx2], df_pixel['r'][idx2], 'r', label='R')
plt.plot(df_pixel['x'][idx2], df_pixel['g'][idx2], 'g', label='G')
plt.plot(df_pixel['x'][idx2], df_pixel['b'][idx2], 'b', label='B')
plt.xlabel('$x$ (pixels)')
plt.ylim(50,120)
plt.legend(frameon=False);